### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by wellescastro** [americofmoliveira/VesselSegmentation_ESWA#1]
Hi Americo! Great work!

I'm wondering if you have plans on providing the source code for replication, it would be very interesting since you obtained good improvements.

Thanks in advance,
Dayvid.

**Comment by americofmoliveira** [comment]
Hi!

The code is available now. Hope it is still useful for you.

Thank you!

**Comment by wellescastro** [comment]
Sure! Thank you!
