### ISSUE TITLE
Another repo for comparison

### ISSUE THREAD

**Issue by lantiga** [americofmoliveira/VesselSegmentation_ESWA#3]
Nice work, you can also take a look at what we did a couple of years back (we just published the repo, we didn't write a paper on it):
https://github.com/orobix/retina-unet

Just as another data point for comparison purposes.

**Comment by americofmoliveira** [comment]
Hi Luca,

In fact, I know your work and it was one of the first points of comparison when I was starting my master's thesis. We ended up not citing the repository in our paper, precisely because there was no associated paper.

Anyway, you guys have a great job over there! Thanks for passing by :)

**Comment by lantiga** [comment]
Thank you Américo, good luck with your studies
