### ISSUE TITLE
How to train the network?

### ISSUE THREAD

**Issue by izhangh** [americofmoliveira/VesselSegmentation_ESWA#5]
Well done! Can you provide training code? Thank you!

**Comment by americofmoliveira** [comment]
Hi,

There is still on-going research based on this work, so I cannot provide training code. You have the weights of the network, just for reproducibility purposes.

Thank you.

**Comment by ZM-J** [comment]
For now could you release your training code please?

**Comment by americofmoliveira** [comment]
Hello,

@ZM-J, access to this work is still restricted by University of Minho.

Please reach out to Prof. Carlos A. Silva (csilva@dei.uminho.pt) to get access to the code.

Thank you.
